<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;22');><img width='50' height='50' src='../../3PC/img_social/Baldi/img/22.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;22');><img border=0 width='50' height='50'  title=':;22' src=./../3PC/img_social/Baldi/img/22.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;21');><img width='50' height='50' src='../../3PC/img_social/Baldi/img/21.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;21');><img border=0 width='50' height='50'  title=':;21' src=./../3PC/img_social/Baldi/img/21.jpg></a>
<%end if%>
