<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_01');><img width='50' height='50' src='../img_social/interfacce/4_01.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_01');><img border=0 width='50' height='50'  title=':;4_01' src=../img_social/interfacce/4_01.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_02');><img width='50' height='50' src='../img_social/interfacce/4_02.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_02');><img border=0 width='50' height='50'  title=':;4_02' src=../img_social/interfacce/4_02.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_03');><img width='50' height='50' src='../img_social/interfacce/4_03.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_03');><img border=0 width='50' height='50'  title=':;4_03' src=../img_social/interfacce/4_03.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_06');><img width='50' height='50' src='../img_social/interfacce/4_06.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_06');><img border=0 width='50' height='50'  title=':;4_06' src=../img_social/interfacce/4_06.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_23');><img width='50' height='50' src='../img_social/interfacce/4_23.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_23');><img border=0 width='50' height='50'  title=':;4_23' src=../img_social/interfacce/4_23.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_05');><img width='50' height='50' src='../img_social/interfacce/4_05.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_05');><img border=0 width='50' height='50'  title=':;4_05' src=../img_social/interfacce/4_05.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_07');><img width='50' height='50' src='../img_social/interfacce/4_07.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_07');><img border=0 width='50' height='50'  title=':;4_07' src=../img_social/interfacce/4_07.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_04');><img width='50' height='50' src='../img_social/interfacce/4_04.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_04');><img border=0 width='50' height='50'  title=':;4_04' src=../img_social/interfacce/4_04.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_08');><img width='50' height='50' src='../img_social/interfacce/4_08.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_08');><img border=0 width='50' height='50'  title=':;4_08' src=../img_social/interfacce/4_08.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_09');><img width='50' height='50' src='../img_social/interfacce/4_09.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_09');><img border=0 width='50' height='50'  title=':;4_09' src=../img_social/interfacce/4_09.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_10');><img width='50' height='50' src='../img_social/interfacce/4_10.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_10');><img border=0 width='50' height='50'  title=':;4_10' src=../img_social/interfacce/4_10.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_11');><img width='50' height='50' src='../img_social/interfacce/4_11.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_11');><img border=0 width='50' height='50'  title=':;4_11' src=../img_social/interfacce/4_11.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_12');><img width='50' height='50' src='../img_social/interfacce/4_12.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_12');><img border=0 width='50' height='50'  title=':;4_12' src=../img_social/interfacce/4_12.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_13');><img width='50' height='50' src='../img_social/interfacce/4_13.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_13');><img border=0 width='50' height='50'  title=':;4_13' src=../img_social/interfacce/4_13.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_14');><img width='50' height='50' src='../img_social/interfacce/4_14.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_14');><img border=0 width='50' height='50'  title=':;4_14' src=../img_social/interfacce/4_14.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_15');><img width='50' height='50' src='../img_social/interfacce/4_15.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_15');><img border=0 width='50' height='50'  title=':;4_15' src=../img_social/interfacce/4_15.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_16');><img width='50' height='50' src='../img_social/interfacce/4_16.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_16');><img border=0 width='50' height='50'  title=':;4_16' src=../img_social/interfacce/4_16.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_17');><img width='50' height='50' src='../img_social/interfacce/4_17.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_17');><img border=0 width='50' height='50'  title=':;4_17' src=../img_social/interfacce/4_17.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_18');><img width='50' height='50' src='../img_social/interfacce/4_18.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_18');><img border=0 width='50' height='50'  title=':;4_18' src=../img_social/interfacce/4_18.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_20');><img width='50' height='50' src='../img_social/interfacce/4_20.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_20');><img border=0 width='50' height='50'  title=':;4_20' src=../img_social/interfacce/4_20.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_21');><img width='50' height='50' src='../img_social/interfacce/4_21.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_21');><img border=0 width='50' height='50'  title=':;4_21' src=../img_social/interfacce/4_21.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_22');><img width='50' height='50' src='../img_social/interfacce/4_22.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_22');><img border=0 width='50' height='50'  title=':;4_22' src=../img_social/interfacce/4_22.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;4_24');><img width='50' height='50' src='../img_social/interfacce/4_24.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;4_24');><img border=0 width='50' height='50'  title=':;4_24' src=../img_social/interfacce/4_24.jpg></a>
<%end if%>
