<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_00');><img width='50' height='50' src='../img_social/navigazione_browser/2_00.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_00');><img border=0 width='50' height='50'  title=':;2_00' src=../img_social/navigazione_browser/2_00.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_01');><img width='50' height='50' src='../img_social/navigazione_browser/2_01.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_01');><img border=0 width='50' height='50'  title=':;2_01' src=../img_social/navigazione_browser/2_01.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_02');><img width='50' height='50' src='../img_social/navigazione_browser/2_02.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_02');><img border=0 width='50' height='50'  title=':;2_02' src=../img_social/navigazione_browser/2_02.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_03');><img width='50' height='50' src='../img_social/navigazione_browser/2_03.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_03');><img border=0 width='50' height='50'  title=':;2_03' src=../img_social/navigazione_browser/2_03.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_04');><img width='50' height='50' src='../img_social/navigazione_browser/2_04.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_04');><img border=0 width='50' height='50'  title=':;2_04' src=../img_social/navigazione_browser/2_04.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_05');><img width='50' height='50' src='../img_social/navigazione_browser/2_05.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_05');><img border=0 width='50' height='50'  title=':;2_05' src=../img_social/navigazione_browser/2_05.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_06');><img width='50' height='50' src='../img_social/navigazione_browser/2_06.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_06');><img border=0 width='50' height='50'  title=':;2_06' src=../img_social/navigazione_browser/2_06.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_07');><img width='50' height='50' src='../img_social/navigazione_browser/2_07.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_07');><img border=0 width='50' height='50'  title=':;2_07' src=../img_social/navigazione_browser/2_07.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_08');><img width='50' height='50' src='../img_social/navigazione_browser/2_08.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_08');><img border=0 width='50' height='50'  title=':;2_08' src=../img_social/navigazione_browser/2_08.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_09');><img width='50' height='50' src='../img_social/navigazione_browser/2_09.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_09');><img border=0 width='50' height='50'  title=':;2_09' src=../img_social/navigazione_browser/2_09.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;2_10');><img width='50' height='50' src='../img_social/navigazione_browser/2_10.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;2_10');><img border=0 width='50' height='50'  title=':;2_10' src=../img_social/navigazione_browser/2_10.jpg></a>
<%end if%>
