   
  <div id="TabbedPanels1" class="TabbedPanels">
  <ul class="TabbedPanelsTabGroup">
    <li class="TabbedPanelsTab" tabindex="0">Emoticons</li>
    <li class="TabbedPanelsTab" tabindex="0">Percezioni</li>
    <li class="TabbedPanelsTab" tabindex="0">Navigazione</li>
    <li class="TabbedPanelsTab" tabindex="0">Umanet Exlorer</li>
    <li class="TabbedPanelsTab" tabindex="0">Interfacce</li>
    <li class="TabbedPanelsTab" tabindex="0">Scheda 6</li>
    <li class="TabbedPanelsTab" tabindex="0">Scheda 7</li>
  </ul>
  <div class="TabbedPanelsContentGroup">
    <div class="TabbedPanelsContent"><!--#include file = "emoticons2.inc"--></div>
    <div class="TabbedPanelsContent"><!--#include file = "connessioni_percezioni2.inc"--></div>
    <div class="TabbedPanelsContent"><!--#include file = "navigazione_browser.inc"--></div>
    <div class="TabbedPanelsContent"><!--#include file = "umanet_explorer.inc"--></div> 
    <div class="TabbedPanelsContent"><!--#include file = "interfacce.inc"--></div>
    <div class="TabbedPanelsContent">Contenuto 6</div>
    <div class="TabbedPanelsContent">Contenuto 7</div>
  </div>
</div>
<script type="text/javascript">
var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
</script>