<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_00');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_0_MatrixOmino_2.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_00');><img border=0 width='50' height='50'  title=':;0_00' src=../cSocial/img_social/connessioni_percezioni/0_0_MatrixOmino_2.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_01');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_1_incredibile_solo.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_01');><img border=0 width='50' height='50'  title=':;0_01' src=../cSocial/img_social/connessioni_percezioni/0_1_incredibile_solo.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_02');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_2_vedoilsole.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_02');><img border=0 width='50' height='50'  title=':;0_02' src=../cSocial/img_social/connessioni_percezioni/0_2_vedoilsole.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_03');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_3_NavigaOcchioSi.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_03');><img border=0 width='50' height='50'  title=':;0_03' src=../cSocial/img_social/connessioni_percezioni/0_3_NavigaOcchioSi.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_04');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_4_MondoCoerenzaVerde.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_04');><img border=0 width='50' height='50'  title=':;0_04' src=../cSocial/img_social/connessioni_percezioni/0_4_MondoCoerenzaVerde.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_05');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_5_LampadinaAccesa.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_05');><img border=0 width='50' height='50'  title=':;0_05' src=../cSocial/img_social/connessioni_percezioni/0_5_LampadinaAccesa.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_06');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_6_TestaAccesa.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_06');><img border=0 width='50' height='50'  title=':;0_06' src=../cSocial/img_social/connessioni_percezioni/0_6_TestaAccesa.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_07');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_7_vedopioggia.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_07');><img border=0 width='50' height='50'  title=':;0_07' src=../cSocial/img_social/connessioni_percezioni/0_7_vedopioggia.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_08');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_8_NavigaOcchioNo.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_08');><img border=0 width='50' height='50'  title=':;0_08' src=../cSocial/img_social/connessioni_percezioni/0_8_NavigaOcchioNo.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_09');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_9_MondoParadossoRosso.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_09');><img border=0 width='50' height='50'  title=':;0_09' src=../cSocial/img_social/connessioni_percezioni/0_9_MondoParadossoRosso.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_10');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_10_LampadinaSpenta.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_10');><img border=0 width='50' height='50'  title=':;0_10' src=../cSocial/img_social/connessioni_percezioni/0_10_LampadinaSpenta.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;0_11');><img width='50' height='50' src='../cSocial/img_social/connessioni_percezioni/0_11_TestaSpenta.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;0_11');><img border=0 width='50' height='50'  title=':;0_11' src=../cSocial/img_social/connessioni_percezioni/0_11_TestaSpenta.jpg></a>
<%end if%>
