<div id='TabbedPanels1' class='TabbedPanels'>
 <ul class='TabbedPanelsTabGroup'> 
   <li class='TabbedPanelsTab' tabindex='0'>Emoticons</li>
   <li class='TabbedPanelsTab' tabindex='0'>Percezione</li>
   <li class='TabbedPanelsTab' tabindex='0'>Navigazione</li>
   <li class='TabbedPanelsTab' tabindex='0'>Umanet Explorer</li>
   <li class='TabbedPanelsTab' tabindex='0'>Interfacce</li>
 </ul> 
<div class='TabbedPanelsContentGroup'>
 <div class='TabbedPanelsContent'><!--#include file = 'smilies.inc'--></div>
 <div class='TabbedPanelsContent'><!--#include file = 'connessioni_percezioni.inc'--></div>
 <div class='TabbedPanelsContent'><!--#include file = 'navigazione_browser.inc'--></div>
 <div class='TabbedPanelsContent'><!--#include file = 'umanet_explorer.inc'--></div>
 <div class='TabbedPanelsContent'><!--#include file = 'interfacce.inc'--></div>
</div>
</div>
<script type='text/javascript'>
var TabbedPanels1 = new Spry.Widget.TabbedPanels('TabbedPanels1');
</script>
