<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_01');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_01.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_01');><img border=0 width='50' height='50'  title=':;3_01' src=../cSocial/img_social/umanet_explorer/3_01.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_02');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_02.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_02');><img border=0 width='50' height='50'  title=':;3_02' src=../cSocial/img_social/umanet_explorer/3_02.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_03');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_03.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_03');><img border=0 width='50' height='50'  title=':;3_03' src=../cSocial/img_social/umanet_explorer/3_03.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_04');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_04.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_04');><img border=0 width='50' height='50'  title=':;3_04' src=../cSocial/img_social/umanet_explorer/3_04.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_05');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_05.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_05');><img border=0 width='50' height='50'  title=':;3_05' src=../cSocial/img_social/umanet_explorer/3_05.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_06');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_06.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_06');><img border=0 width='50' height='50'  title=':;3_06' src=../cSocial/img_social/umanet_explorer/3_06.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_07');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_07.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_07');><img border=0 width='50' height='50'  title=':;3_07' src=../cSocial/img_social/umanet_explorer/3_07.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_08');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_08.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_08');><img border=0 width='50' height='50'  title=':;3_08' src=../cSocial/img_social/umanet_explorer/3_08.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_09');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_09.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_09');><img border=0 width='50' height='50'  title=':;3_09' src=../cSocial/img_social/umanet_explorer/3_09.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_10');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_10.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_10');><img border=0 width='50' height='50'  title=':;3_10' src=../cSocial/img_social/umanet_explorer/3_10.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_11');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_11.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_11');><img border=0 width='50' height='50'  title=':;3_11' src=../cSocial/img_social/umanet_explorer/3_11.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_12');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_12.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_12');><img border=0 width='50' height='50'  title=':;3_12' src=../cSocial/img_social/umanet_explorer/3_12.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_13');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_13.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_13');><img border=0 width='50' height='50'  title=':;3_13' src=../cSocial/img_social/umanet_explorer/3_13.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_14');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_14.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_14');><img border=0 width='50' height='50'  title=':;3_14' src=../cSocial/img_social/umanet_explorer/3_14.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_16');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_16.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_16');><img border=0 width='50' height='50'  title=':;3_16' src=../cSocial/img_social/umanet_explorer/3_16.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_17');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_17.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_17');><img border=0 width='50' height='50'  title=':;3_17' src=../cSocial/img_social/umanet_explorer/3_17.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_18');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_18.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_18');><img border=0 width='50' height='50'  title=':;3_18' src=../cSocial/img_social/umanet_explorer/3_18.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_19');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_19.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_19');><img border=0 width='50' height='50'  title=':;3_19' src=../cSocial/img_social/umanet_explorer/3_19.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_20');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_20.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_20');><img border=0 width='50' height='50'  title=':;3_20' src=../cSocial/img_social/umanet_explorer/3_20.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_21');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_21.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_21');><img border=0 width='50' height='50'  title=':;3_21' src=../cSocial/img_social/umanet_explorer/3_21.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_22');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_22.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_22');><img border=0 width='50' height='50'  title=':;3_22' src=../cSocial/img_social/umanet_explorer/3_22.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_23');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_23.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_23');><img border=0 width='50' height='50'  title=':;3_23' src=../cSocial/img_social/umanet_explorer/3_23.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_24');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_24.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_24');><img border=0 width='50' height='50'  title=':;3_24' src=../cSocial/img_social/umanet_explorer/3_24.jpg></a>
<%end if%>
<%if daShowChat2=0 then%>
<a href=Javascript:postmessage.AddSmileyIcon(':;3_25');><img width='50' height='50' src='../cSocial/img_social/umanet_explorer/3_25.jpg'></a>
<%else%>
<a href=Javascript:addsmile(':;3_25');><img border=0 width='50' height='50'  title=':;3_25' src=../cSocial/img_social/umanet_explorer/3_25.jpg></a>
<%end if%>
