<P><B><A HREF = '../forum/default.asp?id_classe=<%=Session("Id_Classe")%>&divid=<%=Session("divid")%>&cartella=<%=Session("cartella")%>'><font size="1"> Forum </A>
<img src="../forum/img/icon_homepage.gif">
<B><A HREF = 'showChat.asp?id_classe=<%=Session("Id_Classe")%>&divid=<%=Session("divid")%>&cartella=<%=Session("cartella")%>'><font size="1"> Chat </A></p>
<p><b><A HREF = '../cClasse/home_app.asp?id_classe=<%=Session("Id_Classe")%>&divid=<%=Session("divid")%>&cartella=<%=Session("cartella")%>'>Apprendimento</A>  -  <A href="../cClasse/studente_domande.asp?DataClaq=<%=Session("DataClaq")%>&DataClaq2=<%=Session("DataClaq2")%>&id_classe=<%=Session("Id_Classe")%>&classe=<%=Session("cartella")%>&cod=<%=Session("CodiceAllievo")%>"> Quaderno  </A>
 
<A HREF = '../../home_ver.asp?id_classe=<%=Session("Id_Classe")%>&divid=<%=Session("divid")%>&cartella=<%=Session("cartella")%>'>  -  Verifica </A><b></font>
</b></p>