<%
strMessage = Replace(strMessage,":huh?","<a target=_blank href='#'><img title='#' src=smilies/on_1.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":s","<a target=_blank href='#'><img title='#' src=smilies/on_2.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":P","<a target=_blank href='#'><img title='#' src=smilies/on_3.gif align=absmiddle></a>")
strMessage = Replace(strMessage,"}:)","<a target=_blank href='#'><img title='#' src=smilies/on_4.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":D","<a target=_blank href='#'><img title='#' src=smilies/on_5.gif align=absmiddle></a>")
strMessage = Replace(strMessage,"}:|","<a target=_blank href='#'><img title='#' src=smilies/on_6.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":)","<a target=_blank href='#'><img title='#' src=smilies/on_7.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":oops","<a target=_blank href='#'><img title='#' src=smilies/on_8.gif align=absmiddle></a>")
strMessage = Replace(strMessage,";)","<a target=_blank href='#'><img title='#' src=smilies/on_9.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":pff","<a target=_blank href='#'><img title='#' src=smilies/on_10.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":\\","<a target=_blank href='#'><img title='#' src=smilies/on_11.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":0","<a target=_blank href='#'><img title='#' src=smilies/on_12.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":b","<a target=_blank href='#'><img title='#' src=smilies/on_13.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":xx","<a target=_blank href='#'><img title='#' src=smilies/on_14.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":gg","<a target=_blank href='#'><img title='#' src=smilies/on_15.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":nn","<a target=_blank href='#'><img title='#' src=smilies/on_16.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":pp","<a target=_blank href='#'><img title='#' src=smilies/on_17.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":kk","<a target=_blank href='#'><img title='#' src=smilies/on_18.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":yy","<a target=_blank href='#'><img title='#' src=smilies/on_19.gif align=absmiddle></a>")
strMessage = Replace(strMessage,":zz","<a target=_blank href='#'><img title='#' src=smilies/on_20.gif align=absmiddle></a>")
%>
